# Build docker image with which to test pkgnet on r-devel debian
# intended build command to be run from package root:
# 		docker build -f release_testing\dockerfile -t pkgnet_rdevel .

FROM rocker/drd

# Copy test script into container
COPY release_testing/r_devel_check.sh .
RUN chmod +x r_devel_check.sh

# Install System Dependencies
RUN apt-get update
RUN apt-get install -y pandoc pandoc-citeproc qpdf ghostscript libssl-dev libxml2-dev

# Install Devtools
RUN RD -e 'install.packages(c("xml2", "rversions", "roxygen2", "devtools"), repos = "https://cloud.r-project.org")'

# Install R Package Dependencies from source code
COPY . pkgnet/
RUN RD -e 'devtools::install_dev_deps(pkg = "pkgnet/", dependencies=TRUE, repos = "https://cloud.r-project.org")'
RUN rm -rf pkgnet/

# Install R Package Dependencies that somehow get missed in the other process
RUN RD -e 'install.packages(c("webshot", "ggplot2"), repos = "https://cloud.r-project.org")'
RUN RD -e 'webshot::install_phantomjs()'

# Later, during docker run, pkgnet source folder will be included as a mounted volume. 
# That will allow updates to be immediately tested (barring additional package installations).
